Repository Quozul/template, pull requests merged in 2022-11, with the labels that each got.

#7 feat: add gitignore
  .gitignore
Labels: enhancement

#4 docs: code of conduct
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
Labels: documentation

#21 fix: reformat gitignore
  .gitignore
Labels: fix
